import { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Unbounded, Manrope } from "next/font/google";

import "./globals.scss";

const unbounded = Unbounded({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "600"],
  variable: "--display-font",
});

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "700"],
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="uk">
      <body className={`${unbounded.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
