import { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Unbounded, Manrope } from "next/font/google";

import Header from "~/components/header/header";
import Footer from "~/components/footer/footer";

import "./globals.scss";
import styles from "./layout.module.scss";

const unbounded = Unbounded({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "600"],
  variable: "--display-font",
});

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "700"],
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="uk">
      <body className={`${unbounded.variable} ${manrope.variable}`}>
        <div className={styles.layout}>
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
